# Generated by Django 4.2.4 on 2023-08-26 04:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=400)),
                ('email', models.EmailField(default='a@b.com', max_length=254)),
                ('lotacao', models.CharField(max_length=400)),
                ('is_ativo', models.BooleanField(default=True)),
                ('role', models.CharField(default='USER', max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('nome_curso', models.CharField(max_length=400)),
                ('modalidade', models.CharField(max_length=400)),
                ('tipo_reconhecimento', models.CharField(blank=True, max_length=400, null=True)),
                ('ch_curso', models.IntegerField()),
                ('vagas', models.IntegerField()),
                ('categoria', models.CharField(default='', max_length=400)),
                ('competencia', models.CharField(default='', max_length=400)),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('inst_certificadora', models.CharField(max_length=400)),
                ('inst_promotora', models.CharField(max_length=400)),
                ('status', models.CharField(default='PENDENTE', max_length=40)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_valida', models.IntegerField(blank=True, null=True)),
                ('condicao_na_acao', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=40)),
                ('conluido', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc_app.curso')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'inscrições',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='participantes',
            field=models.ManyToManyField(related_name='curso_participante', through='pfc_app.Inscricao', to=settings.AUTH_USER_MODEL),
        ),
    ]
