# Generated by Django 4.2.4 on 2023-08-25 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CH_Valida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_valida', models.IntegerField()),
                ('condicao_na_acao', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=40)),
                ('inscricao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=400)),
                ('lotacao', models.CharField(max_length=400)),
                ('is_ativo', models.BooleanField()),
                ('role', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('nome_curso', models.CharField(max_length=400)),
                ('modalidade', models.CharField(max_length=400)),
                ('tipo_reconhecimento', models.CharField(blank=True, max_length=400, null=True)),
                ('ch_curso', models.IntegerField()),
                ('categoria', models.CharField(default='', max_length=400)),
                ('competencia', models.CharField(default='', max_length=400)),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('inst_certificadora', models.CharField(max_length=400)),
                ('inst_promotora', models.CharField(max_length=400)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(through='pfc_app.CH_Valida', to='pfc_app.participante')),
            ],
        ),
        migrations.AddField(
            model_name='ch_valida',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc_app.curso'),
        ),
        migrations.AddField(
            model_name='ch_valida',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc_app.participante'),
        ),
    ]
