# Generated by Django 4.2.4 on 2023-08-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='participantes',
            field=models.ManyToManyField(related_name='curso_participante', through='pfc_app.CH_Valida', to='pfc_app.participante'),
        ),
    ]
