# Generated by Django 4.2.4 on 2023-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
