# Generated by Django 4.2.4 on 2023-08-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0002_alter_curso_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=40),
        ),
        migrations.AddField(
            model_name='curso',
            name='vagas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
