# Generated by Django 4.2.4 on 2023-09-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0003_alter_statusinscricao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_externo',
            field=models.BooleanField(default=False),
        ),
    ]
