# Generated by Django 4.2.4 on 2023-09-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0006_user_avatar_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
