# Generated by Django 4.2.4 on 2023-10-20 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pfc_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0011_curso_periodo_avaliativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'status validações',
            },
        ),
        migrations.CreateModel(
            name='Validacao_CH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(upload_to=pfc_app.models.user_directory_path)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('ch_solicitada', models.IntegerField(blank=True, null=True)),
                ('ch_confirmada', models.IntegerField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pfc_app.statusvalidacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
