# Generated by Django 4.2.4 on 2023-10-20 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0012_statusvalidacao_validacao_ch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'avaliações'},
        ),
        migrations.AlterModelOptions(
            name='validacao_ch',
            options={'verbose_name_plural': 'validações de CH'},
        ),
        migrations.AlterField(
            model_name='validacao_ch',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pfc_app.statusvalidacao'),
        ),
    ]
