# Generated by Django 4.2.4 on 2023-10-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0013_alter_avaliacao_options_alter_validacao_ch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(default='', max_length=40)),
                ('descricao', models.TextField(default='', max_length=4000)),
            ],
            options={
                'verbose_name_plural': 'certificados',
            },
        ),
    ]
