# Generated by Django 4.2.4 on 2023-10-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0014_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ementa_curso',
            field=models.TextField(default='OLD', max_length=4000),
            preserve_default=False,
        ),
    ]
