# Generated by Django 4.2.4 on 2023-10-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0015_curso_ementa_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='resumo',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='descricao',
            new_name='texto',
        ),
        migrations.AddField(
            model_name='certificado',
            name='cabecalho',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='certificado',
            name='subcabecalho1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='certificado',
            name='subcabecalho2',
            field=models.CharField(default='', max_length=40),
        ),
    ]
