# Generated by Django 4.2.4 on 2023-10-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0016_rename_resumo_certificado_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='cabecalho',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='subcabecalho1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='subcabecalho2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
