# Generated by Django 4.2.4 on 2023-10-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0017_alter_certificado_cabecalho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao_ch',
            name='nome_curso',
            field=models.CharField(default='', max_length=100),
        ),
    ]
