# Generated by Django 4.2.4 on 2023-10-24 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0018_validacao_ch_nome_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
