# Generated by Django 4.2.4 on 2023-10-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0021_alter_validacao_ch_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='certificado_cod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfc_app.certificado'),
        ),
    ]
