# Generated by Django 4.2.4 on 2023-10-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0021_alter_validacao_ch_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao_ch',
            name='data_termino_curso',
            field=models.DateField(default='2023-10-15'),
            preserve_default=False,
        ),
    ]
