# Generated by Django 4.2.4 on 2023-10-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0022_curso_certificado_cod'),
        ('pfc_app', '0022_validacao_ch_data_termino_curso'),
    ]

    operations = [
    ]
