# Generated by Django 4.2.4 on 2023-10-30 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0023_merge_20231030_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimentoCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=40)),
                ('do_requerimento', models.CharField(default='', max_length=2000)),
                ('da_fundamentacao', models.CharField(default='', max_length=1000)),
                ('da_conclusao', models.CharField(default='', max_length=1000)),
                ('rodape', models.CharField(default='', max_length=400)),
            ],
            options={
                'verbose_name_plural': 'certificados',
            },
        ),
        migrations.RemoveField(
            model_name='curso',
            name='certificado_cod',
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='responsavel_analise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_validacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validacao_ch',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='pfc_app.statusvalidacao'),
        ),
        migrations.AlterField(
            model_name='validacao_ch',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerente_validacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='requerimento_ch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfc_app.requerimentoch'),
        ),
    ]
