# Generated by Django 4.2.4 on 2023-10-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0024_requerimentoch_remove_curso_certificado_cod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requerimentoch',
            options={'verbose_name_plural': 'requerimentos'},
        ),
        migrations.AlterField(
            model_name='requerimentoch',
            name='da_conclusao',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='requerimentoch',
            name='da_fundamentacao',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='requerimentoch',
            name='do_requerimento',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='requerimentoch',
            name='rodape',
            field=models.TextField(default='', max_length=400),
        ),
    ]
