# Generated by Django 4.2.4 on 2023-10-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0025_alter_requerimentoch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao_ch',
            name='data_inicio_curso',
            field=models.DateField(default='2023-10-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='instituicao_promotora',
            field=models.CharField(default='', max_length=200),
        ),
    ]
