# Generated by Django 4.2.4 on 2023-12-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0026_validacao_ch_data_inicio_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='eh_evento',
            field=models.BooleanField(default=False, verbose_name='É evento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_externo',
            field=models.BooleanField(default=False, verbose_name='É externo'),
        ),
    ]
