# Generated by Django 4.2.4 on 2023-12-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0027_curso_eh_evento_alter_user_is_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao_ch',
            name='agenda_pfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='ementa',
            field=models.TextField(default=''),
        ),
    ]
