# Generated by Django 4.2.4 on 2024-01-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0029_curso_turma_curso_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao_ch',
            name='condicao_na_acao',
            field=models.CharField(choices=[('DISCENTE', 'DISCENTE'), ('DOCENTE', 'DOCENTE')], default='DISCENTE', max_length=20),
        ),
    ]
