# Generated by Django 4.2.4 on 2024-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0030_validacao_ch_condicao_na_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimentoch',
            name='local_data',
            field=models.TextField(default='', max_length=20),
        ),
    ]
