# Generated by Django 4.2.4 on 2024-01-15 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0033_requerimentoch_rodape2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='inscrito_em',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 18, 20, 2, 77096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='analisado_em',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 18, 20, 2, 77096, tzinfo=datetime.timezone.utc)),
        ),
    ]
