# Generated by Django 4.2.4 on 2024-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0035_alter_inscricao_inscrito_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacao_ch',
            name='analisado_em',
            field=models.DateTimeField(),
        ),
    ]
