# Generated by Django 4.2.4 on 2024-01-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0036_alter_validacao_ch_analisado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacao_ch',
            name='analisado_em',
            field=models.DateField(),
        ),
    ]
