# Generated by Django 4.2.4 on 2024-01-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0037_alter_validacao_ch_analisado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('ativa', models.BooleanField(default=True, verbose_name='Está ativa')),
                ('competencias', models.ManyToManyField(to='pfc_app.competencia')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pfc_app.trilha'),
        ),
    ]
