# Generated by Django 4.2.4 on 2024-01-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0038_competencia_trilha_curso_trilha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='competencia',
        ),
    ]
