# Generated by Django 4.2.4 on 2024-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0039_remove_curso_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='observacao',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
