# Generated by Django 4.2.4 on 2024-01-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0040_curso_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='observacao',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='validacao_ch',
            name='analisado_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
