# Generated by Django 4.2.4 on 2024-01-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0041_alter_curso_observacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota_atributo1',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota_atributo2',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota_atributo3',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota_atributo4',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota_atributo5',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('0', 'N/A')], default=None),
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc_app.tema')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='subtema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pfc_app.subtema'),
            preserve_default=False,
        ),
    ]
