# Generated by Django 4.2.4 on 2024-01-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0042_tema_remove_avaliacao_nota_atributo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoCertificadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='InstituicaoPromotora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subtema',
            options={'verbose_name': 'Avaliação-Subtema'},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'verbose_name': 'Avaliação-Tema'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='inst_certificadora',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='inst_promotora',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
