# Generated by Django 4.2.4 on 2024-01-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0043_instituicaocertificadora_instituicaopromotora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inst_certificadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfc_app.instituicaocertificadora'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='inst_promotora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfc_app.instituicaopromotora'),
        ),
    ]
