# Generated by Django 4.2.4 on 2024-01-18 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0044_alter_curso_inst_certificadora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='carreira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pfc_app.carreira'),
        ),
    ]
