# Generated by Django 4.2.4 on 2024-02-05 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0047_categoria_modalidade_alter_curso_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='validacao_ch',
            name='analisado_em',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='validacao_ch',
            name='responsavel_analise',
            field=models.ForeignKey(default=523, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_validacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
