# Generated by Django 4.2.4 on 2024-02-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0048_alter_inscricao_participante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao_ch',
            name='conhecimento_posterior',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('0', 'N/A')], default='5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='conhecimento_previo',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('0', 'N/A')], default='5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='voce_indicaria',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='8'),
            preserve_default=False,
        ),
    ]
