# Generated by Django 4.2.4 on 2024-03-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0051_alter_validacao_ch_responsavel_analise'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacao_ch',
            name='competencia',
            field=models.ManyToManyField(blank=True, null=True, to='pfc_app.competencia'),
        ),
        migrations.AlterField(
            model_name='validacao_ch',
            name='voce_indicaria',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('0', 'N/A')]),
        ),
    ]
