# Generated by Django 4.2.4 on 2024-03-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0052_validacao_ch_competencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
