# Generated by Django 4.2.4 on 2024-03-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0054_planocurso_curso_planocurso_metodologia_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramaexecucao',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc_app.planocurso'),
        ),
    ]
