# Generated by Django 4.2.4 on 2024-03-08 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0055_alter_cronogramaexecucao_plano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronogramaexecucao',
            options={'verbose_name_plural': 'cronogramas de execução'},
        ),
        migrations.AddField(
            model_name='planocurso',
            name='criado_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planocurso',
            name='quantidade_turma',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Quantidade de turmas'),
        ),
    ]
