# Generated by Django 4.2.4 on 2024-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0056_alter_cronogramaexecucao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planocurso',
            options={'verbose_name': 'plano de curso', 'verbose_name_plural': 'planos de curso'},
        ),
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Horário'),
        ),
    ]
