# Generated by Django 4.2.4 on 2024-03-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0058_relatorio_alter_validacao_ch_competencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrelatorio',
            name='subtema',
        ),
        migrations.AddField(
            model_name='itemrelatorio',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pfc_app.tema'),
            preserve_default=False,
        ),
    ]
