# Generated by Django 4.2.4 on 2024-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0059_remove_itemrelatorio_subtema_itemrelatorio_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtema',
            name='cor',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
