# Generated by Django 4.2.4 on 2024-05-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0062_alter_inscricao_curso_alter_inscricao_participante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(default='', max_length=100)),
                ('link_inscricao', models.CharField(default='', max_length=200)),
                ('carga_horaria_total', models.IntegerField(blank=True, null=True)),
                ('mes_competencia', models.DateField()),
                ('instituicao_promotora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfc_app.instituicaopromotora')),
                ('modalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfc_app.modalidade')),
                ('trilha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfc_app.trilha')),
            ],
        ),
        migrations.AddField(
            model_name='validacao_ch',
            name='curadoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfc_app.curadoria'),
        ),
    ]
