# Generated by Django 4.2.4 on 2024-05-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0063_curadoria_validacao_ch_curadoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curadoria',
            name='cor_circulo',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='curadoria',
            name='permanente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curadoria',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curadorias', to='pfc_app.trilha'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='pfc_app.trilha'),
        ),
    ]
