# Generated by Django 4.2.4 on 2024-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0064_curadoria_cor_circulo_curadoria_permanente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curadoria',
            name='cor_circulo',
        ),
        migrations.AddField(
            model_name='trilha',
            name='cor_circulo',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
