# Generated by Django 4.2.4 on 2024-05-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0065_remove_curadoria_cor_circulo_trilha_cor_circulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='ordem_relatorio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ordem no relatório'),
        ),
    ]
