# Generated by Django 4.2.4 on 2024-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0066_trilha_ordem_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='fundo_tabela',
            field=models.CharField(default='#F3F3F3', max_length=7),
        ),
    ]
